scrollable: false
widgets:
      # TOP BAR
      - !include top_bar.yaml
      - !include bottom_pager.yaml
      - !include bottom_pager_tap_area.yaml
      - !include left_tap_area.yaml
      - !include right_tap_area.yaml
      - !include top_tap_area.yaml
      - !include connecting_view.yaml
                  