globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0"
  - id: pager_dots
    type: int[${total_pages}]
    restore_value: no
  - id: user_is_interacting
    type: bool
    initial_value: "false"
    restore_value: no
  - id: use_24h_clock
    type: bool
    initial_value: "true"
    restore_value: yes
  - id: turn_off_screen_after_value
    type: int
    initial_value: "0"
    restore_value: yes