time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Update clock every minute
      - seconds: 0
        then:
          - script.execute: update_time
    # And on time sync
    on_time_sync:
      then:
        - script.execute: update_time