obj:
  border_width: !lambda |-
    if (${ui_debug_mode}) {
      return 1;
    } else {
      return 0;
    }

label:
  border_width: !lambda |-
    if (${ui_debug_mode}) {
      return 1;
    } else {
      return 0;
    }