substitutions:
  # -----------------------
  # ADJUST DEVICE NAME HERE
  # -----------------------
  device_name: "sensecap-indicator"
  device_friendly_name: "SenseCAP Indicator"

  # --------------------------
  # ENTER API AND OTA KEY HERE
  # --------------------------
  api_key: "<api-key>"
  ota_key: "<ota-key>"

  # ------------------------------
  # ADJUST YOUR WLAN SETTINGS HERE
  # ------------------------------
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # ---------------------------------
  # ADJUST TOTAL NUMBER OF PAGES HERE
  # ---------------------------------
  total_pages: "2" # is used to generate navigation dots and their logic (set it to your pages + 1 for the settings page)

  # --------------
  # OTHER SETTINGS
  # --------------
  user_interface_debug_mode: "false" # Draws borders around objects and labels for layouting
     
sensor:
  # ----------------------------------------------------------------------
  # ADD YOUR SENSORS HERE
  # Because of the way ESPHOME works lights, thermostats, etc also go here
  # ----------------------------------------------------------------------


  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include sensecap-indicator/core/sensors/wifi_signal.yaml
  - !include sensecap-indicator/core/sensors/wifi_signal_percent.yaml
  

binary_sensor:
  # ---------------------
  # ADD YOUR SENSORS HERE
  # ---------------------


  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include sensecap-indicator/core/binary_sensors/indicator_button.yaml
         
switch:
  # ----------------------
  # ADD YOUR SWITCHES HERE
  # ----------------------


  # -----------------------------
  # INTERNAL SWITCHES DON'T TOUCH
  # -----------------------------
  - !include sensecap-indicator/core/switches/use_24h_clock_switch.yaml


lvgl:  
  pages:
    - id: first_page
      bg_color: 0x1b1b1b
      bg_opa: COVER
      widgets:
        # PAGE TITLE
        - !include
            file: sensecap-indicator/user_interface/templates/page_title.yaml
            vars:
              title: "Heating Control"
        - obj:
            styles: content_container
            layout: 
              type: FLEX
              flex_flow: ROW_WRAP
              flex_align_main: LV_FLEX_ALIGN_START
              flex_align_cross: CENTER
            widgets:
              - !include
                  file: sensecap-indicator/user_interface/templates/tiles/info_tile.yaml
                  vars:
                    tile_icon: "\U000F02E3"
                    tile_value: "20.5"
                    tile_unit: "°C"
                    tile_subtitle: "Bedroom"
              - !include
                  file: sensecap-indicator/user_interface/templates/tiles/info_tile.yaml
                  vars:
                    tile_icon: "\U000F04B9"
                    tile_value: "18.0"
                    tile_unit: "°C"
                    tile_subtitle: "Living Room"
              - !include
                  file: sensecap-indicator/user_interface/templates/tiles/info_tile.yaml
                  vars:
                    tile_icon: "\U000F09A0"
                    tile_value: "23.1"
                    tile_unit: "°C"
                    tile_subtitle: "Bathroom"
              - !include
                  file: sensecap-indicator/user_interface/templates/tiles/info_tile.yaml
                  vars:
                    tile_icon: "\U000F09AB"
                    tile_value: "17.5"
                    tile_unit: "°C"
                    tile_subtitle: "Toilet"
              - !include
                  file: sensecap-indicator/user_interface/templates/tiles/info_tile.yaml
                  vars:
                    tile_icon: "\U000F0821"
                    tile_value: "19.4"
                    tile_unit: "°C"
                    tile_subtitle: "Corridor"
   


   # ---------------------------
   # SETTINGS PAGE - DON'T TOUCH
   # ---------------------------
    - !include sensecap-indicator/user_interface/pages/settings.yaml


  # ----------------------
  # INTERNAL - DON'T TOUCH
  # ----------------------
  on_idle: !include sensecap-indicator/core/lvgl/on_idle.yaml
  top_layer: !include sensecap-indicator/core/lvgl/top_layer.yaml
  theme: !include sensecap-indicator/user_interface/theme/theme.yaml
  style_definitions: !include sensecap-indicator/user_interface/theme/style_definitions.yaml


# ----------------------
# INTERNAL - DON'T TOUCH
# ----------------------
<<: !include sensecap-indicator/core/fonts.yaml
<<: !include sensecap-indicator/core/esphome.yaml
<<: !include sensecap-indicator/core/hardware.yaml
<<: !include sensecap-indicator/core/scripts.yaml
<<: !include sensecap-indicator/core/light.yaml
<<: !include sensecap-indicator/core/time.yaml
<<: !include sensecap-indicator/core/select.yaml
<<: !include sensecap-indicator/core/globals.yaml