---
sensor:
  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include core/config/sensors/wifi_signal.yaml
  - !include core/config/sensors/wifi_signal_percent.yaml

binary_sensor:
  # ----------------------------
  # INTERNAL SENSORS DON'T TOUCH
  # ----------------------------
  - !include core/config/binary_sensors/indicator_button.yaml
         
switch:
  # -----------------------------
  # INTERNAL SWITCHES DON'T TOUCH
  # -----------------------------
  - !include core/config/switches/use_24h_clock_switch.yaml

lvgl:
  pages:
   # ---------------------------
   # SETTINGS PAGE - DON'T TOUCH
   # ---------------------------
    - !include user_interface/pages/settings.yaml

  # ----------------------
  # INTERNAL - DON'T TOUCH
  # ----------------------
  disp_bg_color: 0x1b1b1b
  gradients: !include core/config/lvgl/gradients.yaml
  on_idle: !include core/config/lvgl/on_idle.yaml
  top_layer: !include user_interface/pages/top_layer/top_layer.yaml
  theme: !include user_interface/theme/theme.yaml
  style_definitions: !include user_interface/theme/style_definitions.yaml

# ----------------------
# INTERNAL - DON'T TOUCH
# ----------------------
<<: !include core/config/fonts.yaml
<<: !include core/config/esphome.yaml
<<: !include core/config/hardware.yaml
<<: !include core/config/scripts.yaml
<<: !include core/config/light.yaml
<<: !include core/config/time.yaml
<<: !include core/config/select.yaml
<<: !include core/config/globals.yaml

