time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Update clock every minute
      - seconds: 0
        then:
          if:
            condition:
              time.has_time:
            then:
              - script.execute: update_time
    # And on time sync
    on_time_sync:
      then:
        if:
          condition:
            time.has_time:
          then:
            - script.execute: update_time
